### ISSUE TITLE
Requested: Juju Quickstart documentation

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#261]
Juju Quickstart is missing documentation in both official and unofficial capacity in the docs.

**Comment by mitechie** [comment]
Hmm, we should pull some of the docs out from the code currently:

http://bazaar.launchpad.net/~juju-gui/juju-quickstart/trunk/view/head:/quickstart/manage.py

and break it into something that goes through it from 'why' and into the actual arguments/features provided.

**Comment by evilnick** [comment]
As far as the user docs go, I have a page rewriting the  the install/get-started section using quickstart, but we didn't use it at the time because quickstart didn't support MAAS, KVM local or Windows. I know a lot of this has been fixed up now, so maybe that is the way to start.

**Comment by mitechie** [comment]
Quickstart does support maas, it will even auto create your environments.yaml if you're logged into the maas via the api. windows is still an issue. I'm not sure how 'kvm local' is different? Is this just the local juju provider with kvm?

**Comment by marcoceppi** [comment]
Having it documented in the tools section alongside charm tools and the like is a +1 from. As the method in getting-started and as the primary command I'm still a -1 without windows support.

**Comment by evilnick** [comment]
I know it supports MAAS now, which is great.

As for kvm, some of the kvm-specific settings weren't recognised and flagged for removal - I filed a bug https://bugs.launchpad.net/juju-quickstart/+bug/1340226, it hasn't been closed but I guess that doesn't mean it isn't fixed.

**Comment by hatched** [comment]
Has any progress been made here? I feel like the official quickstart documentation should be in the Juju docs as it's such an integral deployment strategy, especially for bundles. So even if it's not in the 'getting started' as mentioned previously can we get a new page with the basics?

**Comment by evilnick** [comment]
Quickstart could and should be added to the tools section, but it isn't a current priority for the docs team this cycle

**Comment by evilnick** [comment]
closing as quickstart no longer relevant
